#!/usr/bin/python

import os, re, sys

for avi in sys.argv[1:]:
        txt = re.sub('avi$', 'txt', avi)
	if os.path.exists(txt):
		print txt + ' exists'
	else:
		cmd = 'gmd5sum "' + avi + '">"' + txt + "\""
		print cmd
		os.system(cmd)

	
