#!/bin/sh
# cope with osx brain damage
# add an unpriviledged user account

set -e

if [ "$(id -u)" != "0" ]; then 
    echo "need to be be root"
    exit 1
fi

read -p "add user: " USER

if [ -z "$USER" ]; then
    echo "aborting..."
    exit 1
fi

# find next unused user and group ids
MAXUID=$(dscl . -list /Users UniqueID | awk '{print $2}' | sort -ug | tail -1)
NEWUID=$((MAXUID+1))
MAXGID=$(dscl . -list /Groups PrimaryGroupID | awk '{print $2}' | sort -ug | tail -1)
NEWGID=$((MAXGID+1))

dscl . -create /Users/$USER
dscl . -create /Users/$USER UserShell /bin/false
dscl . -create /Users/$USER UniqueID $NEWUID
dscl . -create /Groups/$USER
dscl . -create /Groups/$USER PrimaryGroupID $NEWGID
dscl . -create /Users/$USER PrimaryGroupID $NEWGID
dscl . -create /Users/$USER Password '*'
dscl . -create /Users/$USER NFSHomeDirectory /var/empty
echo added user \'$USER\'
